general:
  project_name: tiny_yolo_v2_192
  model_path: ../../stm32ai-modelzoo/object_detection/tiny_yolo_v2/ST_pretrainedmodel_public_dataset/coco_2017_person/tiny_yolo_v2_192/tiny_yolo_v2_192.h5
  model_type: tiny_yolo_v2
  gpu_memory_limit: 16
  num_threads_tflite: 12
  global_seed: 127

operation_mode: chain_eqe

dataset:
  name: coco_2017_person
  class_names:
  - person
  training_path: /local/data/od_coco_2017_person/train
  test_path: /local/data/od_coco_2017_person/test
  quantization_split: 0.001

preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    aspect_ratio: fit
    interpolation: nearest
  color_mode: rgb

postprocessing:
  confidence_thresh: 0.001
  NMS_thresh: 0.5
  IoU_eval_thresh: 0.5
  plot_metrics: false
  max_detection_boxes: 100

quantization:
  quantizer: onnx_quantizer
  target_opset: 17
  granularity: per_channel
  quantization_type: PTQ
  quantization_input_type: float
  quantization_output_type: float
  export_dir: quantized_models

mlflow:
  uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}