general:
   model_path: ../../stm32ai-modelzoo/depth_estimation/fast_depth/Public_pretrainedmodel_public_dataset/nyu_depth_v2/fast_depth_256/fast_depth_256_int8_pc.tflite
   model_type: fast_depth
   
operation_mode: prediction

preprocessing:
   rescaling:
      scale: 1/255
      offset: 0
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

prediction:
   test_files_path: ./datasets/NYU_depth_v2/pred

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
