general:
   model_path: ../../stm32ai-modelzoo/pose_estimation/hand_landmarks/Public_pretrainedmodel_custom_dataset/custom_dataset_heads_468kpts/face_landmarks_v1_192_int8_pc.onnx
   model_type: head_spe

operation_mode: prediction

dataset:
   class_names: [head]
   keypoints: 468

preprocessing:
   rescaling:
      scale: 1/255.
      offset: 0
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

postprocessing:
   kpts_conf_thresh: 0.15

prediction:
   test_files_path: ./datasets/head_test_single_pose

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
